# Generated by Django 4.1.7 on 2025-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
