# Generated by Django 4.1.7 on 2025-02-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easypay', '0003_escolha_delete_escolhas'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolha',
            name='nome',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escolha',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
